CC=D:/MinGW/bin/mingw32-g++
CFLAGS=-std=c++11 -g
INCDIRS=-I. -I..
LIBDIRS=-LD:/MinGW/lib
LIBS=-lmingw32 -lSDL2 -lglew32 -lopengl32 -lfreetype
SOURCES=main.cpp            \
        Shader.cpp          \
        HeightMap.cpp       \
        TargaImage.cpp      \
		Tree.cpp            \
        FreetypeFont.cpp    \
        Md2Model.cpp
TARGET=main
all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(TARGET) $(INCDIRS) $(LIBDIRS) $(LIBS)

